#!/usr/bin/env bash
# .build_docs.sh -- autogenerate the docs site with pdoc: themed (One Dark), self-contained, no
# config files. README.md is the home page; every module under microecs/ becomes its own
# autogenerated API page and shows up in the sidebar "Modules" menu. The theme CSS is embedded
# below (vendored from github.com/nxtlo/syn -> onedark/), so a build needs no network access.
#
#   ./.build_docs.sh            # build into ./docs, then open docs/index.html
#   ./.build_docs.sh public     # build into ./public  (GitLab Pages serves this dir in CI)
set -euo pipefail
cd "$(dirname "$0")"
OUT="${1:-docs}"

# one pure-python build dependency; auto-install so a fresh checkout just works
python -c "import pdoc" 2>/dev/null || { echo "[docs] installing pdoc..."; pip install --quiet pdoc; }

# --- embedded theme + template -> temp dir (pdoc prefers these files over its built-in defaults) ---
TMPL="$(mktemp -d)"
trap 'rm -rf "$TMPL"' EXIT

cat > "$TMPL/theme.css" <<'THEME_CSS'
:root {
  --pdoc-background: #282C34;
}
.pdoc {
  --text: white;
  --muted: whitesmoke;
  --link: var(--lightblue);
  --link-hover: white;
  --active: #555;
  --code: #232627;
  --accent: #232627;
  /* pdoc vars that onedark's theme.css omits -- map onto the palette so nothing falls back to plain text */
  --annotation: var(--orange);
  --def: var(--red);
  --name: var(--purple);
  --nav-hover: var(--dark);
  /* Actual theme colors */
  --lightblue: #61AFEF;
  --red: #E06C75;
  --green: #98C379;
  --dark: #282C34;
  --orange: #E5C07B;
  --purple: #B392F0;
  --blue: #9ECBFF;
  --silver: #ABB2BF;
}
THEME_CSS

cat > "$TMPL/custom.css" <<'CUSTOM_CSS'
body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Noto Sans", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji";
}

.pdoc .il {
  color: #131416;
}

nav.pdoc a.pdoc-button.module-list-button {
  display: none;
}

.pdoc .modulename a:hover {
  color: whitesmoke;
}

.pdoc .classattr {
  color: #fff;
}

.pdoc .docstring .pdoc-code {
  background-color: #232627;
}

.pdoc pre {
  width: fit-content;
}

.pdoc pre a {
  color: whitesmoke;
}

.pdoc pre a:hover {
  color: #676767;
}


/* Submodules and API Doc. */

.pdoc h2 {
  color: #fff;
  font-weight: 0;
  margin: 0.3em 0;
  padding: 0.2em 0;
  content: "Module Content";
}

/* header */
.pdoc h5 {
  color: white;
  font-style: italic;
}

/* Module name */

.pdoc .modulename {
  color: #fff;
  font-weight: 0;
}

.pdoc-code .ow {
  color: var(--red);
}

nav.pdoc a.function {
  color: var(--purple);
}

nav.pdoc a.function:hover {
  background-color: var(--dark);
}

nav.pdoc .function::after {
  content: "";
}

nav.pdoc .function::before {
  content: "fn ";
  color: var(--red);
}

nav.pdoc a.class {
  color: whitesmoke;
}

/* Before the class name. This adds "class 'className'". */
nav.pdoc .class::before {
  content: "class ";
  color: var(--red);
}

/* After the class name. This will remove `()` That comes after the class name. */
nav.pdoc .class::after {
  content: "";
}

nav.pdoc a.class:hover {
  color: #fff;
  background-color: var(--dark);
}

nav.pdoc a.variable {
  color: whitesmoke;
}

/* Adds "var varname" to class variables. */
nav.pdoc a.variable::before {
  content: "var ";
  color: #9d9d9d;
  color: var(--red);
}

nav.pdoc a.variable:hover {
  color: #fff;
  background-color: var(--dark);
}

/* nav modules */
nav.pdoc li a {
  color: var(--purple);
}

nav.pdoc li a:hover {
  background-color: var(--dark);
}

/* Assigned values */
.pdoc span.default_value {
  color: var(--lightblue);
}

.pdoc span.def {
  font-weight: normal;
  color: var(--red);
}

/* 
Attributes
----------
*/
.pdoc h6#attributes {
  color: #fff;
  font-size: 25px;
}

/*
Example
-------
*/

.pdoc h6#example {
  color: #fff;
  font-size: 29px;
}

/* 
Notes
-----
*/

.pdoc h6#notes {
  font-size: 27px;
  color: orange;
}

/* 
Returns
-------
*/

.pdoc h6#returns {
  font-size: 27px;
  color: white;
}

/* 
Parameters
----------
*/

.pdoc h6#parameters {
  font-size: 27px;
  color: white;
}

/*
Raises
------
*/

.pdoc h6#raises {
  font-size: 27px;
  color: rgb(218, 55, 55);
}

/* False, True, None */

.pdoc .kc {
  color: var(--lightblue);
}

.pdoc li {
  color: white;
}

/* Decorator module */

.pdoc .nd {
  color: var(--lightblue);
}

.pdoc b,
strong {
  color: rgba(255, 255, 255, 0.8);
  font-weight: normal;
}

/* colors for .. warning:: and .. note:: */

.pdoc em {
  color: orange;
  font-size: 23px;
}

/* Decorator color */

.pdoc div.decorator {
  color: var(--lightblue);
}

div.pdoc-code.codehilite {
  background-color: var(--code);
}

/* class / function names */

.pdoc span.name {
  color: var(--purple);
  font-weight: normal;
}

/* Inherited class name color */

.pdoc span.base {
  color: whitesmoke;
}

/* Before inherited members colors, i.e., "builtins." */

.pdoc .inherited dt,
.pdoc .inherited dt::before {
  color: var(--silver);
}


/* Commas that separates parameters "," color */
.pdoc .inherited dd:not(:last-child)::after {
  color: #fff;
}

/* Commas that separates parameters "," color */

.pdoc .inherited dd:not(:last-child)::after {
  color: #fff;
}

/* Contents, Submodules, API Documentations */
/* This also can be separated */
.pdoc h1,
.pdoc h2,
.pdoc h3 {
  font-weight: 300;
  margin: 0.3em 0;
  padding: 0.2em 0;
  color: white;
}

/* Top left nav button */
nav.pdoc .module-list-button {
  display: inline-flex;
  align-items: center;
  margin-bottom: 1rem;
  color: white;
  border-color: white;
}

nav.pdoc .module-list-button:hover {
  border-color: white;
  color: white;
}

.pdoc pdoc-alert pdoc-alert-warning .p {
  color: black;
}

.pdoc-code {
  color: white;
}

.pdoc .pdoc-alert-warning {
  color: black;
  background-color: #d5a142;
  border-color: black;
}

.pdoc .pdoc-alert-note {
  color: rgb(7, 19, 24);
  background-color: rgb(184, 231, 251) ;
  border-color: var(--dark);
}

/* The nav bar */

nav.pdoc {
  background-color: rgb(55, 58, 72);
}

.pdoc-code .k {
  color: var(--red);
}

/* === local overrides (microecs) =================================================== */
/* widen the content column (layout.css ships 54rem) by 1.5x so 120-char-wide code
   examples render on a single line, without horizontal scrolling */
main, header { width: calc(81rem + var(--sidebar-width)); }
/* a Home link at the top of the sidebar, above search; styled like the "Modules"/"Contents" headings */
nav.pdoc a.home-button { display: inline-block; color: #fff; font-weight: 300; font-size: 2rem; margin: 0.3em 0; }
nav.pdoc a.home-button:hover { color: var(--lightblue); }
/* README-heading primitives stay code in the body, but render as plain text in the sidebar menu */
nav.pdoc code { font-family: inherit; background: none; color: inherit; padding: 0; border: 0; font-size: inherit; }
CUSTOM_CSS

cat > "$TMPL/syntax-highlighting.css" <<'SYNTAX_CSS'
pre {
  line-height: 125%;
}

td.linenos pre {
  color: #ff5555;
  background-color: #282a36;
  padding-left: 5px;
  padding-right: 5px;
}

span.linenos {
  color: #ff5555;
  background-color: #282a36;
  padding-left: 5px;
  padding-right: 5px;
}

td.linenos pre.special {
  color: #ff5555;
  background-color: #ffffc0;
  padding-left: 5px;
  padding-right: 5px;
}

span.linenos.special {
  color: #ff5555;
  background-color: #ffffc0;
  padding-left: 5px;
  padding-right: 5px;
}

/* This is for the source code docs */

.pdoc-code .hll {
  background-color: #282a36;
}

.pdoc-code {
  background: #282a36;
  color: #ff5555;
}

/* Comment */

.pdoc-code .c {
  color: #6a7aaa;
}

/* Error */
.pdoc-code .err {
  color: #ff5555;
}

/* Keyword */
.pdoc-code .k {
  color: #ff79c6;
}

/* Literal */
.pdoc-code .l {
  color: #ae81ff;
}

/* Name */
.pdoc-code .n {
  color: #f8f8f2;
}

/* Operator */
.pdoc-code {
  color: #ff79c6;
}

/* Punctuation */
.pdoc-code .p {
  color: #f8f8f2;
}

/* Comment.Hashbang */
.pdoc-code .ch {
  color: #6a7aaa;
}

/* Comment.Multiline */
.pdoc-code .cm {
  color: #6a7aaa;
}

/* Comment.Preproc */
.pdoc-code .cp {
  color: #6a7aaa;
}

/* Comment.PreprocFile */
.pdoc-code .cpf {
  color: #6a7aaa;
}

/* Comment.Single */
.pdoc-code .c1 {
  color: var(--silver);
}

/* Comment.Special */
.pdoc-code .cs {
  color: #6a7aaa;
}

/* Generic.Deleted */
.pdoc-code .gd {
  color: #6a7aaa;
}

/* Generic.Emph */
.pdoc-code .ge {
  font-style: italic;
}

/* Generic.Inserted */
.pdoc-code .gi {
  color: #a6e22e;
}

/* Genericutput */
.pdoc-code .go {
  color: whitesmoke;
}

/* Generic.Prompt */
.pdoc-code .gp {
  color: rgb(171, 138, 193);
  font-weight: bold;
}

/* Generic.Strong */
.pdoc-code .gs {
  font-weight: bold;
}

/* Generic.Subheading */
.pdoc-code .gu {
  color: #75715e;
}

/* Keyword.Constant */
.pdoc-code .kc {
  color: white;
}

/* Keyword.Declaration */
.pdoc-code .kd {
  color: rgb(171, 138, 193);
}

/* Keyword.Namespace */
.pdoc-code .kn {
  color: var(--red);
}

/* Keyword.Pseudo */
.pdoc-code .kp {
  color: rgb(171, 138, 193);
}

/* Keyword.Reserved */

.pdoc-code .kr {
  color: rgb(171, 138, 193);
}

/* Keyword.Type */

.pdoc-code .kt {
  color: #ff79c6;
}

.pdoc-code .o {
  color: var(--red);
}

/* Literal.Date */

.pdoc-code .ld {
  color: #e6db74;
}

/* Literal.Number */

.pdoc-code .m {
  color: #ae81ff;
}

/* Literal.String */

.pdoc-code .s {
  color: var(--lightblue);
}

/* Name.Attribute */

.pdoc-code .na {
  color: #a6e22e;
}

/* Name.Builtin */

.pdoc-code .nb {
  color: var(--lightblue);
}

/* Name.Class */

.pdoc-code .nc {
  color: var(--purple);
}

/* Name.Constant */

.pdoc-code .no {
  color: #ff79c6;
}

/* Name.Decorator */

.pdoc-code .nd {
  color: #8be9fd;
}

/* Name.Entity */

.pdoc-code .ni {
  color: #ff79c6;
}

/* Name.Exception */

.pdoc-code .ne {
  color: #8be9fd;
}

/* Name.Function */

.pdoc-code .nf {
  color: var(--purple);
}

/* Name.Label */

.pdoc-code .nl {
  color: #ed9d13;
}

/* Name.Namespace */

.pdoc-code .nn {
  color: #f8f8f2;
}

/* Namether */

.pdoc-code .nx {
  color: #a6e22e;
}

/* Name.Property */

.pdoc-code .py {
  color: #f8f8f2;
}

/* Name.Tag */

.pdoc-code .nt {
  color: #f92672;
}

/* Name.Variable */

.pdoc-code .nv {
  color: #f8f8f2;
}

/* Operator.Word */

.pdoc-code w {
  color: #ff79c6;
}

/* Text.Whitespace */

.pdoc-code .w {
  color: #f8f8f2;
}

/* Literal.Number.Bin */

.pdoc-code .mb {
  color: #ae81ff;
}

/* Literal.Number.Float */

.pdoc-code .mf {
  color: #ae81ff;
}

/* Literal.Number.Hex */
.pdoc-code .mh {
  color: var(--lightblue);
}

/* Literal.Number.Integer */
.pdoc-code .mi {
  color: var(--lightblue);
}

/* Literal.Numberct */
.pdoc-code .mo {
  color: #ae81ff;
}

/* Literal.String.Affix */
.pdoc-code .sa {
  color: var(--red);
}

/* Literal.String.Backtick */
.pdoc-code .sb {
  color: #e6db74;
}

/* Literal.String.Char */
.pdoc-code .sc {
  color: #e6db74;
}

/* Literal.String.Delimiter */
.pdoc-code .dl {
  color: #e6db74;
}

/* Literal.String.Doc */
.pdoc-code .sd {
  color: var(--blue);
}

/* Literal.String.Double */
.pdoc-code .s2 {
  color: var(--blue);
}

/* Literal.String.Escape */
.pdoc-code .se {
  color: var(--lightblue);
}

/* Literal.String.Heredoc */
.pdoc-code .sh {
  color: #e6db74;
}

/* Literal.String.Interpol. AKA f-strings brackets */
.pdoc-code .si {
  color: var(--lightblue);
}

/* Literal.Stringther */
.pdoc-code .sx {
  color: #e6db74;
}

/* Literal.String.Regex */
.pdoc-code .sr {
  color: var(--blue);
}

/* Literal.String.Single */
.pdoc-code .s1 {
  color: var(--blue);
}

span.linenos {
  color: rgb(59, 145, 226);
  background-color: var(--code);
}

/* Literal.String.Symbol */

.pdoc-code .ss {
  color: #e6db74;
}

/* Name.Builtin.Pseudo */
.pdoc-code .bp {
  color: whitesmoke;
}

/* Name.Function.Magic */
.pdoc-code .fm {
  color: var(--lightblue);
}

/* Name.Variable.Class */
.pdoc-code .vc {
  color: #bd93f9;
}

/* Name.Variable.Global */
.pdoc-code .vg {
  color: #f8f8f2;
}

/* Name.Variable.Instance */
.pdoc-code .vi {
  color: #ffffff;
}

/* Name.Variable.Magic */
.pdoc-code .vm {
  color: var(--lightblue);
}

/* Literal.Number.Integer.Long */
.pdoc-code .il {
  color: var(--lightblue);
}
SYNTAX_CSS

# sidebar: show every top-level module on EVERY page (a persistent "Modules" menu), not only on the
# package landing. We override pdoc's nav_submodules block and list every rendered module.
cat > "$TMPL/module.html.jinja2" <<'JINJA'
{% extends "default/module.html.jinja2" %}
{% block module_list_link %}
    <a class="home-button" href="{{ "../" * module.modulename.count(".") }}microecs.html">Home</a>
{% endblock %}
{% block nav_submodules %}
    <h2>Modules</h2>
    <ul>
        {% for name in all_modules|sort if "." in name %}
            <li>{{ (name, "") | link(text=name) }}</li>
        {% endfor %}
    </ul>
{% endblock %}
JINJA

# --- render --------------------------------------------------------------------------------------
rm -rf "$OUT"
python - "$OUT" "$TMPL" <<'PY'
import sys, pathlib, microecs, pdoc, pdoc.render

out, tmpl = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
modules = sorted(p.stem for p in pathlib.Path("microecs").glob("*.py") if not p.stem.startswith("_"))

# Home page = README, with an autogenerated index of the module pages appended. We patch the
# IN-MEMORY module only (the tracked microecs/__init__.py is never touched): README becomes the
# package docstring, and __all__ is emptied so the landing stays README-only -- each class is
# documented on its own module page (linked from the sidebar), never inlined onto the home page.
links = "\n".join(f"- [`microecs.{m}`](microecs/{m}.html)" for m in modules)
microecs.__doc__ = pathlib.Path("README.md").read_text(encoding="utf-8") + f"\n\n## API reference\n\n{links}\n"
microecs.__all__ = []

pdoc.render.configure(template_directory=tmpl)
pdoc.pdoc("microecs", *(f"microecs.{m}" for m in modules), output_directory=out)
PY

echo "[docs] built $OUT/  ->  open file://$(cd "$OUT" && pwd)/index.html"
