image: python:3.12-bullseye

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

test_and_run:
  before_script:
    - pip install -r requirements.txt
    - export PYTHONPATH="$PYTHONPATH:."
  script:
    - python examples/01-moving-colliding-balls.py --help
    - pytest test
